{% set version = "0.7.13" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ezplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ezplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ezplot/ezplot_{{ version }}.tar.gz
  sha256: 6cdec6e0b588eee43c1a13a9af0be88fff8875df37067cabdf30019d3c64eeaa

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-lubridate
    - r-rlang
    - r-tsibble
  run:
    - r-base
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-lubridate
    - r-rlang
    - r-tsibble

test:
  commands:
    - $R -e "library('ezplot')"           # [not win]
    - "\"%R%\" -e \"library('ezplot')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ezplot
  license: MIT
  summary: Wrapper for the 'ggplot2' package that creates a variety of common charts (e.g. bar, line, area, ROC, waterfall, pie) while aiming to reduce typing.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - wkostelecki
    - lc5415

# Package: ezplot
# Type: Package
# Title: Functions for Common Chart Types
# Version: 0.6.1
# Author: Wojtek Kostelecki
# Maintainer: Wojtek Kostelecki <wojtek.kostelecki@gmail.com>
# Description: Wrapper for the 'ggplot2' package that creates a variety of common charts (e.g. bar, line, area, ROC, waterfall, pie) while aiming to reduce typing.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.3)
# RoxygenNote: 7.1.0
# Imports: dplyr, forcats, ggplot2, lubridate, rlang, tsibble
# Suggests: covr, DT, e1071, knitr, methods, miniUI, rmarkdown, ROCR, shiny, stats, testthat, tibble, tidyr, tsibbledata
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-06-13 14:05:37 UTC; wkost
# Repository: CRAN
# Date/Publication: 2020-06-13 14:30:02 UTC
